name: TEST

on:
  workflow_dispatch
#     inputs:
#       logLevel:
#         description: 'Log level'
#         required: true
#         default: 'warning' 
#         type: choice
#         options:
#         - info
#         - warning
#         - debug 
#       test:
#         description: 'test'
#         required: true
#         type: string
  
      
jobs: 
  ci: 
    runs-on: ubuntu-latest
    steps: 
      - name: test1
        id: test1
        run: |
          echo "::set-output name=test::hello"
          
      - name: test
        run: echo ${{steps.test1.outputs.test}}
          


