name: TEST

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
jobs:
  test:
    uses: vickytestcicd/testcicd/.github/workflows/main.yml@master
    with:
      environment: ${{ inputs.environment }}
