name: TEST

on:
  push:
    branches: [main]
#   workflow_dispatch: 
#     inputs: 
#       repository:
#         required: true
#       tag:
#         required: true
      
jobs: 
  ci: 
    runs-on: ubuntu-latest
    steps: 
#       - uses: actions/checkout@v2
#         with:
#           repository: ${{ inputs.repository }}
#           ref: ${{ inputs.tag }}
      - run: |
          export a=0
          export c=$(echo $a|grep1)
          
          if [[ $a -eq null ]]; then echo "test1";else echo "test2";fi
      - run: echo "test"
          
