name: CI

on:
 workflow_call:
  secrets:
    ACCOUNT:
      required: true
    ACCOUNT2:
      required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ secrets.ACCOUNT }}
          echo ${{ secrets.ACCOUNT2 }}
          echo ${{ ACCOUNT }}
          echo ${{ ACCOUNT2 }}
