name: TEST

on:
  push:
    branches: main
  
jobs: 
  ci: 
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check.outputs.result }}
    steps: 
      - name: check
        run: |
          exit 1
        
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - run: echo "test"
