name: TEST

on:
  delete
  
jobs: 
  ci: 
    runs-on: ubuntu-latest
    steps: 
      - run: |
            echo ${{ github.event.ref }}
      - name: check
        run: if[[ ${{ github.event.ref }} =~ ^feature/* ]];echo 'test' ;else echo 'test2'; fi
        
 

