name: TEST

on:
  push:
    branches: main
  
jobs: 
  ci: 
    runs-on: ubuntu-latest
    steps: 
      - name: check
        id: check
        run: |
          export a=feature/test
          if [[ $a =~ ^feature/ ]] ;then echo "::set-output name=test::hello"; else echo 'test2' ;fi
          echo ${{ steps.check.outputs.test }}
      - run: echo ${{ steps.check.outputs.test }}
        
 

