name: TEST

on:
  push:
    branches: [main]
#   workflow_dispatch: 
#     inputs: 
#       repository:
#         required: true
#       tag:
#         required: true
      
jobs: 
  ci: 
    runs-on: ubuntu-latest
    steps: 
      - run: |
          echo ${{ inputs.repository }} 
          echo ${{ inputs.tag }}
          export a=0;
          if a==1;then exit 1;
      - run: echo "test"
          
