name: TEST

on:
  push:
    branches: main
  
jobs: 
  ci: 
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check.outputs.result }}
    steps: 
      - name: check
        run: |
          echo 'test'
        
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - run: echo "test"
      - name: haha
        if: ${{ failure() }}
        run: echo 'failed'
