name: CI

on:
 workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ secrets.ACCOUNT }}
          echo ${{ secrets.ACCOUNT2 }}
          echo ${{ secrets.ACCOUNT }}
          echo ${{ secrets.ACCOUNT2 }}
          echo ${{{ secrets.ACCOUNT }}}
          echo ${{{ secrets.ACCOUNT2 }}}
          echo ${{ secrets.secrets.ACCOUNT }}
          echo ${{ secrets.secrets.ACCOUNT2 }}
          echo ${{ ACCOUNT }}
          echo ${{ ACCOUNT2 }}
