name: CI

on:
 push:
   branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: vickytestcicd/testcicd
          ref: y0.0.1
          fetch-depth: 0
      - run: |
          git branch --contains tags/y0.0.1
      - run: |
          git show y0.0.1


