name: TEST

on:
  workflow_dispatch:
    inputs:
      dbEnv:
        required: true
        type: string
jobs:
  test:
    uses: vickytestcicd/testcicd/.github/workflows/main.yml@master
    with:
      dbEnv: ${{ inputs.dbEnv }}
