name: TEST

on:
  workflow_dispatch:
    inputs:
#       logLevel:
#         description: 'Log level'
#         required: true
#         default: 'warning' 
#         type: choice
#         options:
#         - info
#         - warning
#         - debug 
      test:
        description: 'test'
        required: true
#         type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
env:
  A: dev
  B: pot
  C: sit    
      
jobs: 
  ci: 
    runs-on: ubuntu-latest
    steps: 
      - name: test1
        id: test1
        run: |
          export a=${{ inputs.test }}
          echo ${a##*/}


