name: TEST

on:
  delete:
    reference: [feature/**]
    branches: [feature/**]
    refs: [feature/**]
    ref: [feature/**]
jobs: 
  ci: 
    runs-on: ubuntu-latest
    steps: 
      - run: echo "test"
 

