name: TEST

on:
  delete
  
jobs: 
  ci: 
    runs-on: ubuntu-latest
    steps: 
      - run: |
            echo ${{ github.event.ref }}
            echo ${{ github.event.type }}
      - name: check
        run: if[[ ${{ github.event.type }} -eq 'branch']]; echo 'test' ; else echo 'test2';
        
 

