name: TEST

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'github repository'
        required: true
        type: string
      tag: 
        description: 'github push tag '
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.tag }}
          fetch-depth: 0
      - run: |
          echo ${{ github.api_url }}

    
