name: TEST

on:
  push:
    branches: [main]
#     inputs:
#       logLevel:
#         description: 'Log level'
#         required: true
#         default: 'warning' 
#         type: choice
#         options:
#         - info
#         - warning
#         - debug 
#       test:
#         description: 'test'
#         required: true
#         type: string
  
      
jobs: 
  ci: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: sed -i '/name/{s/$/test/}' values.yaml
      - run: cat values.yaml


