name: TEST

on:
  push:
    branches: [main]
#   workflow_dispatch: 
#     inputs: 
#       repository:
#         required: true
#       tag:
#         required: true
      
jobs: 
  ci: 
    runs-on: ubuntu-latest
    steps: 
      - run: |
          export a=0
          echo $a
          if [[ $a -eq 0 ]]; then echo $a 
          exit 0; fi
      - run: echo "test"
          
