name: TEST

on:
  workflow_dispatch: 
    inputs: 
      repository:
        required: true
      tag:
        required: true
      
jobs: 
  ci: 
    runs-on: ubuntu-latest
    steps: 
      - run: |
          echo ${{ inputs.repository }} 
          echo ${{ inputs.tag }}
          exit 0
          
